#!/usr/bin/env python3
"""
Example script
"""

from CryptoSentWebApp.runner import Runner

if __name__ == '__main__':
    runner = Runner(
        reddit_secrets_path='tst/CryptoSentWebApp/Reddit'
    )
    runner.run()

